meta_product_name: "RunLink"
meta_title: "RunLink - For running enthusiasts"
meta_description: "Connect with other running enthusiasts to keep each other motivated, track your runs while earning badges to celebrate key milestones, and see how you stack up against other runners."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
