meta_product_name: "RunLink"
meta_title: "RunLink - For running enthusiasts"
meta_description: "Connect with other running enthusiasts to keep each other motivated, track your runs while earning badges to celebrate key milestones, and see how you stack up against other runners."
meta_image: "pair_running.jpg" # should exist in `app/assets/images/`
